name: self_distillation
channels:
  - pytorch
  - conda-forge
  - nvidia/label/cuda-11.1.0
  - defaults
dependencies:
  # python version
  - python=3.8

  # cuda, toolkit for pytorch
  # other to compile with nvcc
  - cudatoolkit=11.1

  # core
  - pytorch=1.9
  - pytorch-lightning
  - torchvision=0.10.0
  - matplotlib
  - pip

  # dev
  - black

  - pip:
    # core
    - wandb
    - hesiod==1.0.0
    - torch-cluster==1.6.0
    - torch-geometric==2.0.4
    - torch-points-kernels==0.6.10
    - torch-scatter==2.0.9
    - torch-sparse==0.6.11
    - torch-spline-conv==1.2.1
    - torchaudio==0.9.0
    - torchfile==0.1.0
    - torchmetrics==0.5.0
    - torchnet==0.0.4
    - Hydra==2.5
    - hydra-core==1.1.1
    - setuptools==59.5.0
    - open3d==0.10.0.0
    # dev
    - pytest
